/**
 * CSS transformer — generates CSS custom properties.
 *
 * Output structure:
 *   :root { --token-name: value; }                         ← primitives + global
 *   [data-color-scheme="light"] { ... }                    ← semantic default/light
 *   [data-color-scheme="dark"]  { ... }                    ← semantic default/dark
 *   @media (prefers-color-scheme: dark) { :root { ... } }  ← system dark fallback
 *   [data-brand="brand-a"][data-color-scheme="light"] { } ← brand overrides
 */

import type { ResolvedCollection } from '../token-merger'
import type { TokenValue } from '../messages'

export function generateCSS(collections: ResolvedCollection[]): string {
  const blocks: string[] = [cssHeader()]

  const primitives = collections.find((c) => c.modeName === 'Value' && isPrimitivesCollection(c))
  const global = collections.find((c) => c.modeName === 'Value' && isGlobalCollection(c))
  const semantic = collections.filter((c) => !isPrimitivesCollection(c) && !isGlobalCollection(c))

  // :root — primitives and global tokens
  const rootTokens: Record<string, TokenValue> = {
    ...(primitives?.tokens ?? {}),
    ...(global?.tokens ?? {}),
  }
  if (Object.keys(rootTokens).length > 0) {
    blocks.push(cssBlock(':root', rootTokens))
  }

  // Semantic: group by theme name
  // modeName: "Light" | "Dark" | "Default/Light" | "Brand-A/Light"
  const defaultLight = semantic.find((c) => modeTheme(c.modeName) === 'light' && modeBrand(c.modeName) === 'default')
  const defaultDark  = semantic.find((c) => modeTheme(c.modeName) === 'dark'  && modeBrand(c.modeName) === 'default')

  if (defaultLight) {
    blocks.push(cssBlock('[data-color-scheme="light"]', defaultLight.tokens))
    blocks.push(cssBlock('[data-color-scheme="auto"]', defaultLight.tokens))
  }
  if (defaultDark) {
    blocks.push(cssBlock('[data-color-scheme="dark"]', defaultDark.tokens))
    // System dark mode fallback
    blocks.push(mediaBlock('(prefers-color-scheme: dark)', '[data-color-scheme="auto"]', defaultDark.tokens))
  }

  // Brand overrides
  const brandModes = semantic.filter((c) => modeBrand(c.modeName) !== 'default')
  for (const col of brandModes) {
    const brand = modeBrand(col.modeName)
    const theme = modeTheme(col.modeName)
    const selector = `[data-brand="${brand}"][data-color-scheme="${theme}"]`
    blocks.push(cssBlock(selector, col.tokens))

    if (theme === 'light') {
      blocks.push(cssBlock(`[data-brand="${brand}"][data-color-scheme="auto"]`, col.tokens))
    }
    if (theme === 'dark') {
      blocks.push(
        mediaBlock('(prefers-color-scheme: dark)', `[data-brand="${brand}"][data-color-scheme="auto"]`, col.tokens),
      )
    }
  }

  return blocks.join('\n\n') + '\n'
}

// ---------------------------------------------------------------------------
// Block builders
// ---------------------------------------------------------------------------

function cssBlock(selector: string, tokens: Record<string, TokenValue>): string {
  const entries = Object.entries(tokens)
  if (entries.length === 0) return ''

  const lines = entries.map(([path, token]) => {
    const varName = toCSSVar(path)
    return `  ${varName}: ${token.$value};`
  })

  return `${selector} {\n${lines.join('\n')}\n}`
}

function mediaBlock(
  query: string,
  selector: string,
  tokens: Record<string, TokenValue>,
): string {
  const inner = cssBlock(selector, tokens)
  if (!inner) return ''
  // Indent inner block
  const indented = inner
    .split('\n')
    .map((l) => `  ${l}`)
    .join('\n')
  return `@media ${query} {\n${indented}\n}`
}

function cssHeader(): string {
  return `/**\n * Design tokens — generated by Token Sync\n * Do not edit manually.\n */`
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toCSSVar(path: string): string {
  return '--' + path.replace(/\./g, '-')
}

function modeBrand(modeName: string): string {
  const parts = modeName.split('/')
  if (parts.length === 1) return 'default'
  return parts[0].toLowerCase().replace(/\s+/g, '-')
}

function modeTheme(modeName: string): string {
  const parts = modeName.split('/')
  return parts[parts.length - 1].toLowerCase()
}

function isPrimitivesCollection(c: ResolvedCollection): boolean {
  return c.collectionName.toLowerCase() === 'primitives'
}

function isGlobalCollection(c: ResolvedCollection): boolean {
  return c.collectionName.toLowerCase() === 'global'
}
