/**
 * CSS transformer — generates CSS custom properties.
 *
 * Output structure (Primitives → Themes → Semantic):
 *   :root { ... }                              ← primitives + global + first theme's light.* and dark.* vars
 *   [data-theme="zero"] { ... }                ← non-default theme overrides (only what differs)
 *   [data-color-scheme="light"] { ... }        ← semantic roles → var(--light-*) + resolved severity
 *   [data-color-scheme="dark"] { ... }         ← semantic roles → var(--dark-*) + resolved severity
 *   [data-color-scheme="auto"] + @media        ← follows OS preference
 *
 * Theme switching cascades automatically: changing [data-theme] on any ancestor
 * updates all --light-* and --dark-* CSS vars, which Semantic selectors pick up.
 */

import type { ResolvedCollection, Metadata } from "../token-merger";
import type { TokenValue } from "../messages";
import { resolveFontWeightNumber, DEFAULT_FONT_WEIGHT } from "../font-weight";

export function generateCSS(collections: ResolvedCollection[], metadata: Metadata): string {
  const blocks: string[] = [cssHeader()];

  const names = metadata.figma.collections;
  const primitives = collections.find((c) => c.collectionName === names.primitives);
  const global = collections.find((c) => c.collectionName === names.global);
  const themeCols = collections.filter((c) => c.collectionName === names.themes);
  const semanticCols = collections.filter((c) => c.collectionName === names.semantic);

  // :root — primitives, global, and the default (first) theme's complete light/dark vars
  const defaultTheme = themeCols[0];
  const rootTokens: Record<string, TokenValue> = {
    ...primitives?.tokens,
    ...global?.tokens,
    ...defaultTheme?.tokens, // light.* and dark.* → resolved primitive values
  };
  if (Object.keys(rootTokens).length > 0) {
    blocks.push(cssBlock(":root", rootTokens));
  }

  // Non-default themes — complete light.*/dark.* var set, overriding :root under [data-theme]
  for (const col of themeCols.slice(1)) {
    const themeSlug = col.modeName.toLowerCase().replace(/\s+/g, "-");
    blocks.push(cssBlock(`[data-theme="${themeSlug}"]`, col.tokens));
  }

  // Semantic: Light/Dark modes — emit var(--light-*) / var(--dark-*) for theme-aliased tokens
  const lightCol = semanticCols.find((c) => c.modeName.toLowerCase() === "light");
  const darkCol = semanticCols.find((c) => c.modeName.toLowerCase() === "dark");

  if (lightCol) {
    blocks.push(semanticBlock('[data-color-scheme="light"]', lightCol));
    blocks.push(semanticBlock('[data-color-scheme="auto"]', lightCol));
  }
  if (darkCol) {
    blocks.push(semanticBlock('[data-color-scheme="dark"]', darkCol));
    blocks.push(
      semanticMediaBlock("(prefers-color-scheme: dark)", '[data-color-scheme="auto"]', darkCol),
    );
  }

  return blocks.filter(Boolean).join("\n\n") + "\n";
}

// ---------------------------------------------------------------------------
// Block builders
// ---------------------------------------------------------------------------

/**
 * Semantic block: emits var(--light-*) / var(--dark-*) for {light.*} / {dark.*} raw refs
 * so theme switching cascades automatically, and resolved hex for all other tokens.
 */
function semanticBlock(selector: string, col: ResolvedCollection): string {
  const entries = Object.entries(col.tokens).filter(([, t]) => t.$type !== "boolean");
  if (entries.length === 0) return "";

  const lines = entries.map(([path, token]) => {
    const varName = toCSSVar(path);
    const rawValue = col.rawTokens[path]?.$value;
    const themeAware = toThemeAwareValue(token.$value, rawValue);
    // A var(--light-*)/var(--dark-*) reference is already correct as-is — the value
    // it points to was formatted (including fontWeight conversion) at its own definition.
    const value = themeAware.startsWith("var(")
      ? themeAware
      : formatCSSValue(token.$type, themeAware);
    return `  ${varName}: ${value};`;
  });

  return `${selector} {\n${lines.join("\n")}\n}`;
}

function semanticMediaBlock(query: string, selector: string, col: ResolvedCollection): string {
  const inner = semanticBlock(selector, col);
  if (!inner) return "";
  const indented = inner
    .split("\n")
    .map((l) => `  ${l}`)
    .join("\n");
  return `@media ${query} {\n${indented}\n}`;
}

function cssBlock(selector: string, tokens: Record<string, TokenValue>): string {
  const entries = Object.entries(tokens).filter(([, t]) => t.$type !== "boolean");
  if (entries.length === 0) return "";
  const lines = entries.map(
    ([path, token]) => `  ${toCSSVar(path)}: ${formatCSSValue(token.$type, token.$value)};`,
  );
  return `${selector} {\n${lines.join("\n")}\n}`;
}

function cssHeader(): string {
  return `/**\n * Design tokens — generated by Token Sync\n * Do not edit manually.\n */`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a {light.X} or {dark.X} raw ref to var(--light-X) / var(--dark-X) for the CSS cascade.
 * All other values are returned as-is (resolved hex, dimension, etc.).
 */
function toThemeAwareValue(resolvedValue: string, rawValue: string | undefined): string {
  if (rawValue && /^\{(light|dark)\.[^}]+\}$/.test(rawValue)) {
    // "{light.background.brand}" → "var(--light-background-brand)"
    return `var(${toCSSVar(rawValue.slice(1, -1))})`;
  }
  return resolvedValue;
}

function toCSSVar(path: string): string {
  return "--" + path.replace(/\./g, "-");
}

/**
 * `fontWeight` tokens hold Figma's named font style ("SemiBold") — CSS `font-weight`
 * only accepts `normal`/`bold` or a number 100-900, so this converts via the DTCG
 * alias table, falling back to DEFAULT_FONT_WEIGHT (with a warning) rather than
 * emitting an invalid declaration.
 */
function formatCSSValue($type: string, value: string): string {
  if ($type === "fontWeight") {
    const resolved = resolveFontWeightNumber(value);
    if (resolved === null) {
      console.warn(
        `[TokenSync] Unrecognized font weight "${value}" — using ${DEFAULT_FONT_WEIGHT}`,
      );
    }
    return String(resolved ?? DEFAULT_FONT_WEIGHT);
  }
  return value;
}
