/**
 * Swift transformer — generates Swift structs with static let constants.
 */

import type { ResolvedCollection, Metadata } from "../token-merger";
import type { TokenValue } from "../messages";

function swiftHeader(): string {
  return `// Design tokens — generated by Token Sync
// Do not edit manually.

import SwiftUI`;
}

function toSwiftFieldName(path: string): string {
  // "color.brand.500" → "colorBrand500"
  return path
    .split(".")
    .map((segment, i) =>
      i === 0
        ? segment.toLowerCase().replace(/[^a-z0-9]/g, "")
        : segment.charAt(0).toUpperCase() +
          segment
            .slice(1)
            .toLowerCase()
            .replace(/[^a-zA-Z0-9]/g, ""),
    )
    .join("");
}

function swiftStructName(modeName: string): string {
  // "Light" → "Light", "Default/Light" → "Light", "Brand-A/Dark" → "BrandADark"
  return (
    modeName
      .split("/")
      .map((p) => p.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string) => (c ? c.toUpperCase() : "")))
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("")
      .replace("Default", "") || "Default"
  );
}

function toSwiftValue(token: TokenValue): string | null {
  const v = token.$value;

  // Boolean
  if (token.$type === "boolean") return v === "true" ? "true" : "false";

  // Color: #rrggbb or #rrggbbaa
  const hexMatch = v.match(/^#([0-9a-f]{6})([0-9a-f]{2})?$/i);
  if (hexMatch) {
    return `Color(hex: "${v.toUpperCase()}")`;
  }

  // Color: rgba(r, g, b, a)
  const rgbaMatch = v.match(/^rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)$/);
  if (rgbaMatch) {
    const [, r, g, b, a] = rgbaMatch;
    return `Color(red: ${r}/255.0, green: ${g}/255.0, blue: ${b}/255.0, opacity: ${a})`;
  }

  // Dimension: "16px" → 16.0
  const pxMatch = v.match(/^([\d.]+)px$/);
  if (pxMatch) return `${parseFloat(pxMatch[1])}`;

  // Number string
  if (/^[\d.]+$/.test(v)) return v;

  // String
  if (typeof v === "string") return `"${v.replace(/"/g, '\\"')}"`;

  return null;
}

function swiftType(token: TokenValue): string {
  if (token.$type === "boolean") return "Bool";
  const v = token.$value;
  if (v.startsWith("#") || v.startsWith("rgba(")) return "Color";
  if (/^[\d.]+px$/.test(v) || /^[\d.]+$/.test(v)) return "Double";
  return "String";
}

function swiftStruct(structName: string, tokens: Record<string, TokenValue>): string {
  const lines: string[] = [`public struct ${structName} {`];

  for (const [path, token] of Object.entries(tokens)) {
    const fieldName = toSwiftFieldName(path);
    const swiftVal = toSwiftValue(token);
    if (swiftVal === null) continue;

    const type = swiftType(token);
    lines.push(`    public static let ${fieldName}: ${type} = ${swiftVal}`);
  }

  lines.push("}");
  return lines.join("\n");
}

const colorExtension = `// MARK: - Color Extension Helper
#if canImport(SwiftUI)
@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: // RGB (12-bit)
            (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: // ARGB (32-bit)
            (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}
#endif`;

export function generateSchemeSwift(
  primitivesCol: ResolvedCollection | undefined,
  globalCol: ResolvedCollection | undefined,
  schemeCol: ResolvedCollection,
): string {
  const blocks: string[] = [swiftHeader()];

  if (primitivesCol) {
    blocks.push(swiftStruct("DesignTokensPrimitives", primitivesCol.tokens));
  }

  const mergedTokens: Record<string, TokenValue> = {
    ...(globalCol?.tokens ?? {}),
    ...schemeCol.tokens,
  };

  blocks.push(swiftStruct("DesignTokens", mergedTokens));
  blocks.push(colorExtension);

  return blocks.join("\n\n") + "\n";
}

export function generateSwift(collections: ResolvedCollection[], metadata: Metadata): string {
  const blocks: string[] = [swiftHeader()];

  const names = metadata.figma.collections;
  const primitives = collections.find((c) => c.collectionName === names.primitives);
  const global = collections.find((c) => c.collectionName === names.global);
  const semantic = collections.filter((c) => c.collectionName === names.semantic);

  if (primitives) {
    blocks.push(swiftStruct("DesignTokensPrimitives", primitives.tokens));
  }
  if (global) {
    blocks.push(swiftStruct("DesignTokensGlobal", global.tokens));
  }
  for (const col of semantic) {
    const structName = "DesignTokens" + swiftStructName(col.modeName);
    blocks.push(swiftStruct(structName, col.tokens));
  }

  blocks.push(colorExtension);

  return blocks.join("\n\n") + "\n";
}
